management:
  endpoints:
    web:
      exposure:
        include: "refresh"

polar:
  greeting: "Welcome to the catalog from the catalog service!"

server:
  port: 9001
  tomcat:
    connection-timeout: "2s"
    keep-alive-timeout: "15s"
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: "catalog-service"
  cloud:
    config:
      uri: "http://localhost:8888"
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false
      retry:
        max-attempts: 5
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1

  config:
    import: "optional:configserver:"

  datasource:
    username: "user"
    password: "password"
    url: "jdbc:postgresql://localhost:15432/polardb_catalog"
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5